<?xml version="1.0" encoding="utf-8"?><Database Name="mtgcards" Class="CardsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=mtgcards;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mtgcardsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cards" Member="Cards">
    <Type Name="Card">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeckId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CardName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>